[package]
name = "rustfm"
version = "0.1.1"
edition = "2021"
license = "MIT"

[package-metadata]
authors = ["QMVCopr. <qmvscorpio@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
